"""Refresh IDX universe constituent lists (IDX30 / LQ45 / IDX80 / Kompas100).

IDX rebalances these indices every ~6 months. The built-in lists in
`src/saham_id/data/universe.py` are hardcoded snapshots and will drift
over time. This script fetches fresh constituents and writes a new
`universe.py` module on demand.

SOURCES
-------
Primary (free, unofficial):
    - yfinance — tickers with `.JK` suffix
    - Wikipedia pages for index compositions (often outdated)
Better (recommended for production):
    - IDX's "IDX Stock Index Handbook" PDF, refreshed per announcement:
      https://www.idx.co.id/en/market-data/stock-data/index-data/
    - CSV downloads from vendors: datasaham.io, sectors.app, Stockbit.

STRATEGY
--------
This script supports two modes:

    1. `--source file --input constituents.csv`
       Read a CSV with columns `index,ticker` and regenerate the Python
       file. You provide the CSV from an official download.

    2. `--source manual`
       Interactive mode: print the current hardcoded lists + a diff
       template, so you can paste updated tickers into the file yourself.

Example usage:
    python scripts/update_universe.py \\
        --source file --input data/raw/idx_constituents.csv \\
        --output src/saham_id/data/universe.py
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path


TEMPLATE = '''"""Stock universes — predefined ticker lists for IDX indices.

Auto-generated by scripts/update_universe.py.
Last refreshed: {generated_at}
Source: {source_label}

IDX rebalances these indices every ~6 months. Re-run the update script
when IDX announces a new composition.
"""

from __future__ import annotations

from typing import Iterable


IDX30: list[str] = {idx30!r}

LQ45: list[str] = {lq45!r}

IDX80: list[str] = {idx80!r}

KOMPAS100: list[str] = {kompas100!r}


UNIVERSES: dict[str, list[str]] = {{
    "IDX30": IDX30,
    "LQ45": LQ45,
    "IDX80": IDX80,
    "KOMPAS100": KOMPAS100,
}}


def get_universe(name: str) -> list[str]:
    """Return a universe by name (case-insensitive)."""
    key = name.upper()
    if key not in UNIVERSES:
        valid = ", ".join(sorted(UNIVERSES))
        raise ValueError(f"Unknown universe '{{name}}'. Valid: {{valid}}")
    return list(UNIVERSES[key])


def list_universes() -> Iterable[str]:
    return sorted(UNIVERSES.keys())


def to_yahoo_symbols(tickers: Iterable[str]) -> list[str]:
    """Convert plain IDX tickers to Yahoo Finance format (BBCA -> BBCA.JK)."""
    return [f"{{t.upper()}}.JK" if not t.endswith(".JK") else t.upper() for t in tickers]
'''


def read_csv_constituents(path: Path) -> dict[str, list[str]]:
    """Parse a CSV with `index,ticker` columns into a {index_name: [tickers]} dict."""
    by_index: dict[str, set[str]] = defaultdict(set)
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        required = {"index", "ticker"}
        if set(reader.fieldnames or []) < required:
            raise ValueError(
                f"CSV must have columns {sorted(required)}; "
                f"got {reader.fieldnames}"
            )
        for row in reader:
            idx = row["index"].strip().upper()
            tk = row["ticker"].strip().upper().removesuffix(".JK")
            if idx and tk:
                by_index[idx].add(tk)
    return {k: sorted(v) for k, v in by_index.items()}


def render_universe_module(
    idx30: list[str],
    lq45: list[str],
    idx80: list[str],
    kompas100: list[str],
    source_label: str,
) -> str:
    """Return Python source for `universe.py`."""
    from datetime import datetime

    return TEMPLATE.format(
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        source_label=source_label,
        idx30=sorted(set(idx30)),
        lq45=sorted(set(lq45)),
        idx80=sorted(set(idx80)),
        kompas100=sorted(set(kompas100)),
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update IDX universe constituent lists.",
    )
    parser.add_argument(
        "--source",
        choices=("file", "manual"),
        default="manual",
        help="file = read --input CSV; manual = print current lists",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Path to CSV with columns: index,ticker",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/saham_id/data/universe.py"),
        help="Output module path",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated module to stdout instead of writing",
    )
    args = parser.parse_args()

    if args.source == "manual":
        print(
            "Manual mode — printing current hardcoded lists from the "
            "installed universe.py module.\n"
            "To refresh automatically, supply `--source file --input <csv>`.\n"
        )
        try:
            from saham_id.data import universe as u
        except ImportError as exc:
            print(f"Cannot import universe module: {exc}", file=sys.stderr)
            return 1
        for name in u.list_universes():
            tickers = u.UNIVERSES[name]
            print(f"[{name}] {len(tickers)} tickers")
            for t in tickers:
                print(f"  {t}")
            print()
        print(
            "Next step: obtain the official composition from IDX "
            "(https://www.idx.co.id/), save as CSV with columns "
            "`index,ticker`, then re-run with `--source file`."
        )
        return 0

    # `file` mode
    if not args.input or not args.input.exists():
        print(
            "Error: --input CSV not found. Provide --input path/to/constituents.csv",
            file=sys.stderr,
        )
        return 2

    by_index = read_csv_constituents(args.input)
    required_keys = {"IDX30", "LQ45", "IDX80", "KOMPAS100"}
    missing = required_keys - set(by_index)
    if missing:
        print(f"Warning: CSV missing indices {sorted(missing)} — they'll be empty")
    source_label = f"CSV: {args.input}"
    module_src = render_universe_module(
        idx30=by_index.get("IDX30", []),
        lq45=by_index.get("LQ45", []),
        idx80=by_index.get("IDX80", []),
        kompas100=by_index.get("KOMPAS100", []),
        source_label=source_label,
    )

    if args.dry_run:
        print(module_src)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(module_src)
    print(f"Wrote {args.output}")
    print(
        f"  IDX30={len(by_index.get('IDX30', []))} "
        f"LQ45={len(by_index.get('LQ45', []))} "
        f"IDX80={len(by_index.get('IDX80', []))} "
        f"KOMPAS100={len(by_index.get('KOMPAS100', []))}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
